# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=1000)),
                ('hints', models.CharField(max_length=1000)),
                ('answer', models.CharField(default='n', max_length=100, null=True)),
            ],
        ),
    ]
