# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-21 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.IntegerField(default=0)),
                ('articlename', models.CharField(max_length=100)),
            ],
        ),
    ]
