# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-21 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articles',
            new_name='article',
        ),
    ]
