# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181021_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='binaryarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.IntegerField(default=0)),
                ('articlename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cryptoarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.IntegerField(default=0)),
                ('articlename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='forensicsarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.IntegerField(default=0)),
                ('articlename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='generalarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.IntegerField(default=0)),
                ('articlename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='webarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.IntegerField(default=0)),
                ('articlename', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='article',
            new_name='reversingarticle',
        ),
    ]
