# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181021_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('articleid', models.IntegerField(primary_key=True, serialize=False)),
                ('articlecategory', models.CharField(max_length=100)),
                ('articlename', models.CharField(max_length=100)),
                ('articlecontent', models.CharField(max_length=1000000000000)),
                ('writtenby', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
