# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_article_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='binaryarticle',
        ),
        migrations.DeleteModel(
            name='cryptoarticle',
        ),
        migrations.DeleteModel(
            name='forensicsarticle',
        ),
        migrations.DeleteModel(
            name='generalarticle',
        ),
        migrations.DeleteModel(
            name='reversingarticle',
        ),
        migrations.DeleteModel(
            name='webarticle',
        ),
    ]
